#!/bin/bash
setup_locale(){
  case $OSTYPE in
    darwin*)
      declare -r locale=en_CA.UTF-8
      ;;
    linux-gnu)
      declare -r locale=en_CA.utf8
      ;;
  esac
  declare -r no_locale_msg=$( cat <<EOF
\n
This system does not have $locale installed.
You can install it using the following:
[sudo] locale-gen $locale
[sudo] update-locale LANG=$locale

Then you can simply source this file again:
source ~/.bash_locale && setup_locale $locale
\n
EOF
)

  if locale -a | grep -q $locale ; then
    export LC_ALL="$locale"
    export LANG="$locale"
    export LANGUAGE="$locale"
  else
    printf "$no_locale_msg"
  fi
}

setup_locale
