#!/bin/bash
#FIXME presumably defunct, figure out what has changed since 2014
# start agent and set environment variables, if needed
start_agent(){
  if env | grep -q SSH_AGENT_PID; then
    echo "ssh agent running [SSH_AGENT_PID='$SSH_AGENT_PID']."
  elif env | grep -q SSH_AUTH_SOCK; then
    echo "ssh agent forwarding mode [SSH_AUTH_SOCK='$SSH_AUTH_SOCK']."
  else
    echo "ssh agent not running (SSH_AGENT_PID empty), starting ssh-agent ..."
    eval $( ssh-agent -s )
    start_agent # will print SSH_AGENT_PID
  fi
}

add_identity(){
  if ! ssh-add -l >/dev/null 2>&-; then
    ssh-add
  fi
}

# FIXME gnome-keyring bug (6 years old):
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=472477
# https://bugs.launchpad.net/ubuntu/+source/openssh/+bug/505278
# https://bugs.launchpad.net/ubuntu/+source/gnome-keyring/+bug/1271591
remove_identity(){
  if env | grep -q SSH_AGENT_PID; then
    ssh-add -D
    unset SSH_AGENT_PID
    unset SSH_AUTH_SOCK
  fi
}

[[ -x /usr/bin/ssh-agent ]] && start_agent && add_identity
