#!/bin/bash

set -u
# find the real username and home directory in case this is a non-login shell,
# e.g. in a docker build.
USER=$( whoami )
HOME=$( eval echo ~$USER )
CUR_DIR="$(dirname "$0")"
[ $USER = root ] && sudo= || sudo=sudo
if which rcup >/dev/null; then
  RCUP=rcup
else
  log 'rcm not installed; using rcup.sh instead'
  RCUP=$CUR_DIR/rcup.sh
fi
RCUP_OPTS="-f -v -d '$CUR_DIR' -x install -x README.md -x rcup.sh"


log(){ printf -- "---> $1\n" >&2; }

privileged(){
  if [ $USER = root ]; then
    return 0
  else
    which sudo >/dev/null && sudo -l >/dev/null 2>&1
    return $?
  fi
}

install_rcm() {
  log 'Installing rcm ...'
  case $OSTYPE in
    darwin*)
      brew tap thoughtbot/formulae
      brew install rcm
      ;;
    linux-gnu)
      declare -r deb_src='https://thoughtbot.github.io/rcm/debs/rcm_1.3.0-1_all.deb'
      declare -r deb_dst=$HOME/rcm.deb
      wget -qO "$deb_dst" "$deb_src" && $sudo dpkg -i "$deb_dst" >/dev/null 2>&1
      ;;
  esac
}

install_pubkey(){
  local ssh_conf_dir=$HOME/.ssh
  local gh_api_url='https://api.github.com/users/amirkdv/keys'
  mkdir -p "$ssh_conf_dir" && chmod 700 "$ssh_conf_dir"
  authorized_keys=$ssh_conf_dir/authorized_keys
  # the ssh-import-id package currently does not
  touch $authorized_keys && chmod 600 $authorized_keys

  local pubkey_installed=
  if which ssh-import-id >/dev/null 2>&1; then
    if ssh-import-id gh:amirkdv >/dev/null 2>&1; then
      log 'fetched public key via ssh-import-id gh:amirkdv'
      return 0
    else
      log "ssh-import-id failed, potentially since versions below 3.x do not support GitHub"
      log "falling back on $gh_api_url"
    fi
  else
    log "ssh-import-id not found, falling back on $gh_api_url"
  fi
  local key="$(wget -qO- "$gh_api_url" | grep key | cut -d'"' -f4)"
  if [ "$key" = '' ]; then
    log "Failed to fetch public key from $gh_api_url"
    return 1
  else
    printf "$key\n" >> "$authorized_keys"
    log "$key"
  fi
}

main(){
  case "$1" in
    dotfiles)
      log 'installing dotfiles'
      $RCUP $RCUP_OPTS
      return $?
      ;;
    rcup.sh)
      log 'regenerating rcup.sh'
      if [ $RCUP != rcup ]; then
        log 'rcm needs to be installed to generate standalone scripts'
        return 1
      fi
      # 1. for some reason fails unless it's in bash -c!
      # 2. don't evaluate HOME here, let it be evaluated where we run rcup.sh
      # 3. don't hardcode the PWD here, let it remain relative
      HOME='$HOME' bash -c "rcup $RCUP_OPTS -g" | sed "s|$(readlink -f $CUR_DIR)/||" > $1
      return $?
      ;;
    pubkey)
      install_pubkey
      return $?
      ;;
    locale)
      if privileged; then
        $sudo locale-gen en_CA.utf8 && $sudo update-locale LANG=en_CA.utf8
        return $?
      else
        log 'Installing locale requires root privileges'
        return 1
      fi
      ;;
    *)
      log "I don't know what to do with $1"
      return 1
      ;;
  esac
}

[ $# = 0 ] && log 'specify what to install: dotfiles|pubkey|locale|rcup.sh' && exit 1
code=0
for i in "$@"; do
  main "$i"
  if [ $? -eq 0 ]; then
    log "Successfully installed $i"
  else
    log "Failed to install $i"
    code=1
  fi
done
exit $code
