#!/bin/sh
#
# Usage:
#
#    sh install.sh
#
# Environment variables: VERBOSE, CP, LN, MKDIR, RM, DIRNAME, XARGS.
#
#    env VERBOSE=1 sh install.sh
#
# DO NOT EDIT THIS FILE
# 
# This file is generated by rcm(7) as:
#
#   rcup -f -v -d . -x install -x README.md -x rcup.sh -g
#
# To update it, re-run the above command.
#
: ${VERBOSE:=0}
: ${CP:=/bin/cp}
: ${LN:=/bin/ln}
: ${MKDIR:=/bin/mkdir}
: ${RM:=/bin/rm}
: ${DIRNAME:=/usr/bin/dirname}
: ${XARGS:=/usr/bin/xargs}
verbose() {
  if [ "$VERBOSE" -gt 0 ]; then
    echo "$@"
  fi
}
handle_file_cp() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $DIRNAME "$2" | $XARGS $MKDIR -p
  $CP -R "$1" "$2"
}
handle_file_ln() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $DIRNAME "$2" | $XARGS $MKDIR -p
  $LN -sf "$1" "$2"
}
handle_file_ln "./atom/config.cson" "$HOME/.atom/config.cson"
handle_file_ln "./atom/keymap.cson" "$HOME/.atom/keymap.cson"
handle_file_ln "./atom/styles.less" "$HOME/.atom/styles.less"
handle_file_ln "./bash_aliases" "$HOME/.bash_aliases"
handle_file_ln "./bash_locale" "$HOME/.bash_locale"
handle_file_ln "./bash_logout" "$HOME/.bash_logout"
handle_file_ln "./bash_prompt" "$HOME/.bash_prompt"
handle_file_ln "./bashrc" "$HOME/.bashrc"
handle_file_ln "./bash_ssh_agent" "$HOME/.bash_ssh_agent"
handle_file_ln "./config/matplotlib/matplotlibrc" "$HOME/.config/matplotlib/matplotlibrc"
handle_file_ln "./foo.go" "$HOME/.foo.go"
handle_file_ln "./gitconfig" "$HOME/.gitconfig"
handle_file_ln "./mlterm/aafont" "$HOME/.mlterm/aafont"
handle_file_ln "./mlterm/color" "$HOME/.mlterm/color"
handle_file_ln "./mlterm/main" "$HOME/.mlterm/main"
handle_file_ln "./npm-packages/gitkeep" "$HOME/.npm-packages/gitkeep"
handle_file_ln "./npmrc" "$HOME/.npmrc"
handle_file_ln "./rcm_1.3.0-1_all.deb" "$HOME/.rcm_1.3.0-1_all.deb"
handle_file_ln "./tmux.conf" "$HOME/.tmux.conf"
handle_file_ln "./vim/after/ftplugin/markdown.vim" "$HOME/.vim/after/ftplugin/markdown.vim"
handle_file_ln "./vim/after/ftplugin/php.vim" "$HOME/.vim/after/ftplugin/php.vim"
handle_file_ln "./vim/after/syntax/yaml.vim" "$HOME/.vim/after/syntax/yaml.vim"
handle_file_ln "./vim/colors/molokai.vim" "$HOME/.vim/colors/molokai.vim"
handle_file_ln "./vim/doc/NERD_commenter.txt" "$HOME/.vim/doc/NERD_commenter.txt"
handle_file_ln "./vim/ftdetect/dockerfile.vim" "$HOME/.vim/ftdetect/dockerfile.vim"
handle_file_ln "./vim/ftdetect/drupal.vim" "$HOME/.vim/ftdetect/drupal.vim"
handle_file_ln "./vim/ftdetect/go.vim" "$HOME/.vim/ftdetect/go.vim"
handle_file_ln "./vim/ftdetect/markdown.vim" "$HOME/.vim/ftdetect/markdown.vim"
handle_file_ln "./vim/ftdetect/vagrantfile.vim" "$HOME/.vim/ftdetect/vagrantfile.vim"
handle_file_ln "./vim/ftplugin/go.vim" "$HOME/.vim/ftplugin/go.vim"
handle_file_ln "./vim/ftplugin/javascript.vim" "$HOME/.vim/ftplugin/javascript.vim"
handle_file_ln "./vim/ftplugin/php.vim" "$HOME/.vim/ftplugin/php.vim"
handle_file_ln "./vim/ftplugin/python.vim" "$HOME/.vim/ftplugin/python.vim"
handle_file_ln "./vim/ftplugin/rst.vim" "$HOME/.vim/ftplugin/rst.vim"
handle_file_ln "./vim/ftplugin/ruby.vim" "$HOME/.vim/ftplugin/ruby.vim"
handle_file_ln "./vim/plugin/dbgpavim.py" "$HOME/.vim/plugin/dbgpavim.py"
handle_file_ln "./vim/plugin/dbgpavim.vim" "$HOME/.vim/plugin/dbgpavim.vim"
handle_file_ln "./vim/plugin/NERD_commenter.vim" "$HOME/.vim/plugin/NERD_commenter.vim"
handle_file_ln "./vim/syntax/codex.vim" "$HOME/.vim/syntax/codex.vim"
handle_file_ln "./vim/syntax/dockerfile.vim" "$HOME/.vim/syntax/dockerfile.vim"
handle_file_ln "./vim/syntax/go.vim" "$HOME/.vim/syntax/go.vim"
handle_file_ln "./vim/syntax/markdown.vim" "$HOME/.vim/syntax/markdown.vim"
handle_file_ln "./vim/syntax/textile.vim" "$HOME/.vim/syntax/textile.vim"
handle_file_ln "./vim/syntax/todo.vim" "$HOME/.vim/syntax/todo.vim"
handle_file_ln "./vimrc" "$HOME/.vimrc"
